# Generated by Django 4.2.2 on 2023-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addmin', '0002_delete_ode'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_otp', models.IntegerField()),
            ],
        ),
    ]
