# Generated by Django 4.2.2 on 2023-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0004_mtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtn',
            name='Maker',
            field=models.CharField(default='', max_length=100),
        ),
    ]
