# Generated by Django 4.2.2 on 2023-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0006_mtn_campany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtn',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
