# Generated by Django 4.2.2 on 2023-10-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0008_airtell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtell',
            name='R_Number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mtn',
            name='R_Number',
            field=models.CharField(max_length=50),
        ),
    ]
