# Generated by Django 4.2.6 on 2023-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0009_alter_airtell_r_number_alter_mtn_r_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Had_cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationary', models.IntegerField()),
                ('agent', models.IntegerField()),
            ],
        ),
    ]
