# Generated by Django 4.2.6 on 2023-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0010_had_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campany', models.CharField(max_length=200)),
                ('Credit', models.CharField(max_length=200)),
                ('Debit', models.CharField(max_length=200)),
                ('Time', models.DateTimeField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
